[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_dao = "5L8Gqfw28KQUTTny47HitnDXf5QVnkEqQKFynWgJ9P9W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mhokzone/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
